services:
  db_sso:
    image: postgres
    container_name: postgres_sso
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 12345
    volumes:
      - sso_db:/var/lib/postgresql/date
    networks:
      - project
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

#  pgadmin4:
#    image: elestio/pgadmin:latest
#    restart: always
#    environment:
#      PGADMIN_DEFAULT_EMAIL: your_username
#      PGADMIN_DEFAULT_PASSWORD: 12345
#      PGADMIN_LISTEN_PORT: 8085
#    ports:
#      - "8085:8085"
#    volumes:
#      - ./servers.json:/pgadmin4/servers.json
#    networks:
#      - project
  goose_migration:
    image: migration:1
    container_name: migration
    networks:
      - project
    environment:
      HOST_POSTGRES: postgres_sso
      DB_NAME: postgres
      USER_NAME: postgres
      USER_PASS: 12345
      MIGRATIONS_PATH: ./bin/app/migration_db
    depends_on:
      db_sso:
        condition: service_healthy

  sso_backend:
    image: sso_backend:1
    container_name: sso_backend
    environment:
      CONFIG_PATH: ./config.yaml
    networks:
      - project
    ports:
      - 8080:8080
    depends_on:
      db_sso:
        condition: service_healthy

volumes:
  sso_db:
    name: sso_db
  post_comment_db:
    name: post_comment_db

networks:
  project:
    name: project



