env: "production"
database_url: "host=postgres_sso dbname=postgres user=postgres password=12345 port=5432"
server:
  mail_sender: "your email"
  mail_password: "your password"
  timeout: 1h
  idletimeout: 1h
  token_ttl: 1h
  url_accepter: "http://your_host/accepter"
  address: "0.0.0.0"
  port: 8080
